/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontSize: {
        'xs': ['0.875rem', { lineHeight: '1.25rem' }],
        'sm': ['1rem', { lineHeight: '1.5rem' }],
        'base': ['1.125rem', { lineHeight: '1.75rem' }],
        'lg': ['1.25rem', { lineHeight: '1.75rem' }],
        'xl': ['1.5rem', { lineHeight: '2rem' }],
        '2xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '3xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '4xl': ['3rem', { lineHeight: '1' }],
        '5xl': ['3.75rem', { lineHeight: '1' }],
        '6xl': ['4.5rem', { lineHeight: '1' }],
      },
      colors: {
        primarygray: "#f8f8f8",
        qblack: "#222222",
        qyellow: "#F19042",
        qred: "#EF262C",
        qgray: "#797979",
        qblacktext: "#1D1D1D",
        qgraytwo: "#8E8E8E",
        "qgray-border": "#EFEFEF",
        "qblue-white": "#CBECFF",
        "qh2-green": "#2D6F6D",
        "qh4-pink": "#FDB2BB",
        "qh5-bwhite": "#95D7DE",
        "qh3-blue": "#1868D5",
        // Button colors
        primary: "#FE9F43",
        "primary-hover": "#e68a3a",
        secondary: "#6b7280",
        "secondary-hover": "#374151",
        success: "#16a34a",
        "success-hover": "#15803d",
        danger: "#dc2626",
        "danger-hover": "#b91c1c",
        warning: "#eab308",
        "warning-hover": "#ca8a04",
        info: "#2563eb",
        "info-hover": "#1d4ed8",
        light: "#f3f4f6",
        "light-hover": "#e5e7eb",
        dark: "#1f2937",
        "dark-hover": "#111827",
      },
      scale: {
        60: "0.6",
      },
    },
  },
  variants: {
    extend: {
      textColor: ["focus-within"],
      borderStyle: ["last"],
    },
  },
  // plugins: [],
};
