name: Deploy bitsgiga-client

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bitsgiga-client:latest
          provenance: false

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull & restart stack
        run: |
          cd /srv/projects/bitsgiga
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f
