name: Build & Deploy to Prod

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: prod-deploy
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push bitsgiga-client
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # GHCR requires lowercase repo/image names
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/bitsgiga-client:main
            ghcr.io/${{ secrets.GHCR_USERNAME }}/bitsgiga-client:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/bitsgiga-client:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ secrets.GHCR_USERNAME }}/bitsgiga-client:buildcache,mode=max
          # uncomment if your home server is ARM64
          # platforms: linux/amd64,linux/arm64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server & deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /srv/projects/bitsgiga/prod
            # login to GHCR (safe even if already logged in)
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            # pull and recreate client
            docker compose pull bitsgiga-client
            docker compose up -d bitsgiga-client
            docker image prune -f --filter "until=240h" || true
