name: Build & Deploy to Prod

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: prod-deploy
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Login to GHCR using built-in token
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Lowercase owner for GHCR paths
      - name: Lowercase owner
        run: echo "OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_ENV

      - name: Build & Push bitsgiga-client
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/bitsgiga-client:main
            ghcr.io/${{ env.OWNER }}/bitsgiga-client:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER }}/bitsgiga-client:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER }}/bitsgiga-client:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, linux, x64, prod]   # <- labels you gave your server runner
    steps:
      - name: Pull & restart client on server
        run: |
          set -euo pipefail
          cd /srv/projects/bitsgiga/prod
          OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GHCR_READ_TOKEN }}" | docker login ghcr.io -u "$OWNER" --password-stdin
          docker compose pull bitsgiga-client
          docker compose up -d bitsgiga-client
          docker image prune -f --filter "until=240h" || true
