name: Deploy bitsgiga-client (self-hosted)

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-bitsgiga-client
  cancel-in-progress: true

jobs:
  deploy:
    # if you added a custom label when registering the runner, include it here
    runs-on: self-hosted
    steps:
      - name: Deploy from repo on server
        run: |
          set -euo pipefail
          cd /srv/projects/bitsgiga/bitsgiga-client
          # use the deploy key you generated for this server
          export GIT_SSH_COMMAND='ssh -i /home/runner/.ssh/bitsgiga_client_key -o IdentitiesOnly=yes'
          git fetch --all --prune
          git reset --hard origin/main
          docker compose up -d --build --remove-orphans
          docker image prune -f

      - name: Smoke test (edge)
        run: |
          code=$(curl -sS -o /dev/null -w "%{http_code}" https://bitsgiga.com || echo 0)
          echo "HTTP $code"
          test "$code" -ge 200 -a "$code" -lt 500
